env:
  DOCKER_REPO: europe-docker.pkg.dev/vaxine/vaxine-io
  IMAGE_NAME: vaxine

agent:
  docker: true
  gcp: true

steps:
  - label: ":whale: Build & push the vaxine container"
    command: make buildkite-build-and-push

