env:
  DOCKER_REPO: europe-docker.pkg.dev/vaxine/electric-sql
  DOCKERHUB_REPO: electricsql
  IMAGE_NAME: vaxine

agent:
  docker: true
  gcp: true

steps:
  - label: ":whale: Build & push the vaxine container"
    command: git fetch --tags && make buildkite-build-and-push
  - wait
  - label: ":rocket: Publish the image to DockerHub"
    if: build.tag =~ /^[0-9]+\.[0-9]+\.[0-9]+/
    env:
      DOCKER_REPO: electricsql
      TAG_AS_LATEST: "true"
    command:
      - git fetch --tags
      - export ELECTRIC_IMAGE_NAME="${DOCKERHUB_REPO}/${IMAGE_NAME}"
      - make buildkite-build-and-push
