env:
  DOCKER_REPO: europe-docker.pkg.dev/vaxine/vaxine-io
  IMAGE_NAME: antidote

agent:
  docker: true
  gcp: true

steps:
  - label: ":whale: Build & push the antidote container"
    command:
      - "SHORTSHA=$(echo $BUILDKITE_COMMIT | head -c 7)"
      - "docker build -f Dockerfile.antidote -t ${DOCKER_REPO?}/${IMAGE_NAME?}:latest -t ${DOCKER_REPO?}/${IMAGE_NAME?}:$$SHORTSHA ."
      - "docker push ${DOCKER_REPO?}/${IMAGE_NAME?}:$$SHORTSHA"
      - "docker push ${DOCKER_REPO?}/${IMAGE_NAME?}:latest"
