env:
  DOCKER_REPO: europe-docker.pkg.dev/vaxine/vaxine-io
  IMAGE_NAME: vaxine

agent:
  docker: true
  gcp: true

steps:
  - label: ":whale: Build & push the vaxine container"
    command:
      - "SHORTSHA=$(echo $BUILDKITE_COMMIT | head -c 7)"
      - "docker buildx build --platform linux/arm64/v8,linux/amd64 --push -f Dockerfile.vaxine -t ${DOCKER_REPO?}/${IMAGE_NAME?}:latest -t ${DOCKER_REPO?}/${IMAGE_NAME?}:$$SHORTSHA ."

